version: '3.7'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    command: pytest -sv --alluredir=allure-results --html=report.html
