name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  ui-tests:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:
      #clone repo
      - uses: actions/checkout@v2

      - name: Prepare Allure
        run: |
          mkdir -p allure-results
          
      - name: Run tests via docker-compose
        run: |
          docker compose build tests
          docker compose up tests

      - name: Copy Allure history
        run: |
          mkdir -p allure-results/history
          sudo cp -R ./.github/gh-pages/ allure-results/history/
         
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-results

      - name: Publish Allure report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-results
