name: Run tests via Docker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v3

      - name: Checkout gh-pages to GitHub runner
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Docker layer cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image with cache
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
            -t my-tests:cached .

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run tests in container
        run: |
          docker run --rm -v ${{ github.workspace }}/allure-results:/usr/workspace/allure-results my-tests:cached

      - name: Prepare allure history
        run: |
          mkdir -p allure-results/history
          cp -R ./.github/gh-pages/last-history/* allure-results/history/ || echo "No history to copy"

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-results

      - name: Publish Allure report on GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-results
